In [4]:
import pandas as pd 
import numpy as np

In [17]:
df = pd.read_csv("/Users/henrilehodey/code/jojibou/invesscience/raw_data/founders.csv")
df
df = df.rename(columns=())

,person_object_id,permalink,normalized_name,api_path,web_path,api_url,gender,facebook_url,twitter_url,linkedin_url
0,p:10,mark-zuckerberg,mark zuckerberg,people/mark-zuckerberg,person/mark-zuckerberg,https://api.crunchbase.com/v3.1/people/mark-zu...,Male,https://www.facebook.com/zuck,https://twitter.com/finkd,NaN
1,p:25830,ben-padnos,ben padnos,people/ben-padnos,person/ben-padnos,https://api.crunchbase.com/v3.1/people/ben-padnos,Male,http://www.facebook.com/benpadnos,http://twitter.com/benpadnos,http://www.linkedin.com/in/benpadnos
2,p:258233,subba-rao-ambati,subba rao ambati,people/subba-rao-ambati,person/subba-rao-ambati,https://api.crunchbase.com/v3.1/people/subba-r...,Female,NaN,NaN,NaN
3,p:258253,enrico-fiorentin,enrico fiorentin,people/enrico-fiorentin,person/enrico-fiorentin,https://api.crunchbase.com/v3.1/people/enrico-...,Male,NaN,NaN,NaN
4,p:258257,mark-de-quervain,mark de quervain,people/mark-de-quervain,person/mark-de-quervain,https://api.crunchbase.com/v3.1/people/mark-de...,Male,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
53827,p:185880,paul-meyer,paul meyer,people/paul-meyer,person/paul-meyer,https://api.crunchbase.com/v3.1/people/paul-meyer,Male,NaN,NaN,http://www.linkedin.com/pub/paul-meyer/0/18/b97
53828,p:252514,aashish-kumar,aashish kumar,people/aashish-kumar,person/aashish-kumar,https://api.crunchbase.com/v3.1/people/aashish...,Male,http://www.facebook.com/aashishkumarr,http://twitter.com/aashishkumarr,http://www.linkedin.com/in/aashikumar
53829,p:134554,thomas-fast,thomas fast,people/thomas-fast,person/thomas-fast,https://api.crunchbase.com/v3.1/people/thomas-...,Male,NaN,http://twitter.com/thomasfast,NaN
53830,p:58971,paul-parisi,paul parisi,people/paul-parisi,person/paul-parisi,https://api.crunchbase.com/v3.1/people/paul-pa...,Male,NaN,NaN,NaN
53831,p:99998,adam-neumann,adam neumann,people/adam-neumann,person/adam-neumann,https://api.crunchbase.com/v3.1/people/adam-ne...,Male,NaN,http://twitter.com/noizwaves,http://www.linkedin.com/in/adamneumann

# keeping women

In [25]:
df_women = df[~df.gender.isin(Female)]
df_women.shape

NameError: name 'Female' is not defined